#!/bin/bash
# rc: description: Load kernel modules
# rc: depends: mountvirtfs
# rc: hd-opts: -no
. /etc/rc.d/lib/functions.sh

[[ -e /proc/modules ]] || exit 0

msg_pending "Loading modules..."

[[ -r /etc/modules.load ]]		|| exit 0
egrep -qv '^($|#)' /etc/modules.load	|| exit 0

while read module args; do
	case "$module" in
		""|"#"*) continue;;
	esac
	modprobe ${module} ${args} >/dev/null || \
		failedmod="$failedmod $module"
done < /etc/modules.load

msg_ok "Modules loaded"
[[ -n "$failedmod" ]] && \
	msg_fail "Failed to load: $failedmod" && exit 1

exit 0
