#!/bin/bash

[[ "$install_inits" == "yes" ]] || exit 0

mv /etc/init.d	/etc/init.d~
mv /etc/inittab /etc/inittab~

mkdir /etc/init.d
cp -vr initscripts/init.d/* /etc/init.d/
cp -vr initscripts/init.d/.shutdown /etc/init.d/
cp -v  initscripts/inittab  /etc/inittab
