#!/bin/bash

case $2 in
	shutdown) 
		runlvl="shutdown"
		echo	"halt: $(ls -1 $1 | tr '\n' ' ')"
		echo -e	"\t/etc/init.d/.shutdown/sendsignals; /etc/init.d/.shutdown/umount; /etc/init.d/.shutdown/halt"
		echo	"reboot: $(ls -1 $1 | tr '\n' ' ')"
		echo -e	"\t/etc/init.d/.shutdown/sendsignals; /etc/init.d/.shutdown/umount; /etc/init.d/.shutdown/reboot"
	;;
	sysinit) 
		runlvl="sysinit"
		echo	"sysinit: $(ls -1 $1 | tr '\n' ' ')"
	;;
	*)
		RUNLEVELS=(1 2 3 4 5)
		echo -n "stopall: " 
		for SCRIPT   in $(ls -1 $1)
		do
			case $SCRIPT in
				user|sysinit|shutdown|disabled|enabled) continue;;
			esac
			echo -n "stop_$SCRIPT "
		done
		echo
		for RUNLEVEL in "${RUNLEVELS[@]}"
		do
			export RUNLEVEL
			echo "$RUNLEVEL: $(cat ./$RUNLEVEL/depends | tr '\n' ' ')" 
			unset RUNLEVEL
		done
		;;
esac

for initscript in $(ls -1 $1)
do
	case $initscript in
		user|sysinit|shutdown|disabled|enabled) continue;;
	esac
	STOPABILITY="$(awk '/# rc: script-stop:/ { $1=$2=$3=""; print $0; }' $1/$initscript)"
	INITSCRIPT_USER="$(awk '/# rc: run-as:/  { $1=$2=$3=""; print $0; }' $1/$initscript)"
	HD_COMMAND_LINE="$(awk '/# rc: hd-opts:/ { $1=$2=$3=""; print $0; }' $1/$initscript)"
	echo 	"$initscript: $(awk '/# rc: depends:/ { $1=$2=$3=""; print $0; }' $1/$initscript)"
		echo -e "\tRUNLEVEL=\"$runlvl\" HD_OPTS=\"${HD_COMMAND_LINE}\" USER=\"${INITSCRIPT_USER}\" service _start $initscript"
	echo    "stop_$initscript: $(awk '/# rc: stop-depends:/ { $1=$2=$3=""; print $0; }' $1/$initscript)"
		echo -e "\tSTOPABILITY=\"${STOPABILITY}\" service _stop $initscript"
done
