#!/bin/bash

RUNLEVELS=(S 0 1 2 3 4 5 6)
for RUNLEVEL in "${RUNLEVELS[@]}"
do
	export RUNLEVEL
	echo "$RUNLEVEL: $(cat ./$RUNLEVEL/depends | tr '\n' ' ')" 
	unset RUNLEVEL
done

for initscript in $(ls -1 $1)
do
	{ [[ "$initscript" == "lib" ]] || [[ "$initscript" == "Makefile" ]]; } && continue
	INITSCRIPT_USER="$(awk '/# rc: run-as:/  { $1=$2=$3=""; print $0; }' $1/$initscript)"
	HD_COMMAND_LINE="$(awk '/# rc: hd-opts:/ { $1=$2=$3=""; print $0; }' $1/$initscript)"
	echo 	"$initscript: $(awk '/# rc: depends:/ { $1=$2=$3=""; print $0; }' $1/$initscript)"
	echo -e "\t{ [[ -f /run/service/$initscript/pid ]] || [[ \"\`cat /run/service/$initscript/status\`\" == \"exited=0*\" ]]; } || { \\"
	echo -e "\tcd $1 && \\"
	echo -e	"\tRUN_DAEMON_USER=\"${INITSCRIPT_USER}\" /sbin/hd ${HD_COMMAND_LINE:--o} -s ./$initscript; \\"
	echo -e "\t}"
	echo -e "stop_$initscript:"
	echo -e "\tservice stop $initscript"
done
