#!/bin/bash

[[ "$UID" == 0 ]] || \
	{ echo "hrdrc: must be superuser"; exit 1; }

mountpoint /run &>/dev/null || {
	mount /run
}

mkdir /run/service &>/dev/null

stop_services(){
	cd /etc/rc.d 
	make -s stopall -j
}

case $1 in
	S)
		cd /etc/rc.d/sysinit
		echo 
		echo -e "\t\e[1;32mhardclanz-init\e[0m \e[1mis booting\e[0m \e[1;34m$(cat /etc/hostname)\e[0m" | tee /dev/kmsg
		echo
		lastboot=$(cat /var/tmp/lastboot)
		(( currentboot = lastboot + 1 ))
		echo $currentboot > /run/bootnum
		echo $(date) > /run/bootdate
		make -s $1 -j || /sbin/sulogin
		echo "hrdrc: Reached runlevel: S" > /dev/kmsg
		touch /run/.s_done
		echo $(cat /run/bootnum) $(cat /run/bootdate) >> /var/tmp/boottable
		[[ -n $init_stop ]] && /bin/bash
		;;
	[1-5])
		cd /etc/rc.d
		stop_services
		make -s $1 -j || /sbin/sulogin
		echo "hrdrc: Reached runlevel: $1" > /dev/kmsg
		;;
	0)
		cat /run/bootnum > /var/tmp/lastboot
		cd /etc/rc.d/shutdown
		stop_services
		{ make -s 0 -j && make -s halt; } || /sbin/sulogin
		;;
	6)
		cat /run/bootnum > /var/tmp/lastboot
		cd /etc/rc.d/shutdown
		stop_services
		{ make -s 6 -j && make -s reboot; } || /sbin/sulogin
		;;
	*)
		echo "hrdrc: Usage: hrdrc [0-6]"
		exit 1
		;;
esac
exit
