#!/bin/bash

[[ "$UID" == 0 ]] || \
	{ echo "hrdrc: must be superuser"; exit 1; }

mountpoint /run &>/dev/null || {
	mount /run
	mkdir /run/service
	chmod +rw $_
}

case $1 in
	[0-6])
		cd /etc/rc.d
		exec make $1 -j
		;;
	*)
		echo "hrdrc: Usage: hrdrc [0-6]"
		exit 1
		;;
esac
