#!/bin/bash

[[ "$UID" == 0 ]] || \
	{ echo "hrdrc: must be superuser"; exit 1; }

mountpoint /run &>/dev/null || {
	mount /run
}
mkdir /run/service
case $1 in
	[1-5]|S)
		cd /etc/rc.d
		exec make -s $1 -j
		;;
	0)
		cd /etc/rc.d
		make -s 0 -j && make -s halt
		;;
	6)
		cd /etc/rc.d
		make -s 6 -j && make -s reboot
		;;
	*)
		echo "hrdrc: Usage: hrdrc [0-6]"
		exit 1
		;;
esac
